---
# Apache Webserver 설치 후 구동하는 Ansible descript
# AWS에서 처리 가능하도록
# 약간 수정함 18.9.27
- name: apache install
  hosts: webserver
  become: yes
  become_method: sudo
  tasks:
    - name: install apache with yum
      yum: name=httpd state=installed
    - name: start httpd
      service: name=httpd state=started enabled=yes
