---
- name: apache install
  hosts: webserver
  become: yes
  become_method: sudo
  tasks:
    - name: install apache with yum 
      yum: name=httpd state=installed
    - name: start httpd
      service: name=httpd state=started enabled=yes
